### ISSUE TITLE
Cleansed data for HP/Kullu

### ISSUE THREAD

**Issue by AJ-72** [pratapvardhan/NFHS-5#3]
I couldn't add the sheet to the gdoc. So did it in my workspace and have shared. Here is the link:
https://docs.google.com/spreadsheets/d/1d-2VZM_6YRwregw2W5g09L15TwxvVAImJGmjwXSsfAo/edit?usp=sharing

**Comment by AJ-72** [comment]
Ah my bad. I see that Kullu was already done. Will push a different one.

**Comment by pratapvardhan** [comment]
@AJ-72 -- given access.
