### ISSUE TITLE
Potential issue with tabula/tabulizer's area detection

### ISSUE THREAD

**Issue by jvargh7** [pratapvardhan/NFHS-5#5]
Great job @pratapvardhan ! I was working on this in parallel in R and noticed that when I had a PDF of varying table area, tabulizer applies the first page's area. Thane (MH) is a case-in-point where the google doc has also spilled to NFHS-4. Happy to collaborate and flag for other states/districts where this could be happening.

**Comment by pratapvardhan** [comment]
Great work @jvargh7! 👏

I think, Thane and HP-Kangra too might have the issue, for now I'm planning to do manual edit and push, and figure that slowly. Happy to get onto a call if you'd like to catchup sometime.

**Comment by pratapvardhan** [comment]
In newer PDFs this issue appears mostly with HP state only. Using a different method with Tabula fixes it.
