### ISSUE TITLE
Manual QC check of data

### ISSUE THREAD

**Issue by snishmeet1699** [pratapvardhan/NFHS-5#6]
Hi Pratap
We are manually conducting quality of your data download with the factsheet. Will keep you posted of any issues.

Thanks!

**Comment by pratapvardhan** [comment]
Thanks for helping @snishmeet1699

**Comment by rajrohan205** [comment]
Hey @pratapvardhan,

Thank you very much for extracting these datasets. This is really really great.
We did a manual and thorough data quality check of the data you extracted with the state and district factsheets. We did not find any error in the state-level datasets. However, in the district level dataset, there was one particular error that was consistent across (almost) all the districts. Indicator #58, in your dataset, is "58. Children age   9-59 months who received a vitamin A dose in the last 6 months (%)" whereas in the current district factsheets its "58 Children age 9-35 months who received a vitamin A dose in the last 6 months (%)". So, basically, your data reports Vitamin A dose for children aged 9-59 months whereas the district factsheets have this data for the age group 9-35 months. And the numbers (percentages) are also obviously different.

My guess is that the factsheets themselves have been updated on the NFHS site and indicator 58 has been replaced with the current one. But happy to hear what according to you might be the reason.

Apart from this, there was no error in the district-level datasets as well.

Thanks,
Rohan

**Comment by pratapvardhan** [comment]
@rajrohan205 thanks for raising this. I'll take a look and update here.

**Comment by pratapvardhan** [comment]
@rajrohan205 -- this is fixed in 5ac3049 with pdfs as of today. Could you check now?

**Comment by rajrohan205** [comment]
I looked at the data for few districts and those look good now.
